name: app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+210

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  firebase_core: ^1.4.0
  latlong2: ^0.8.0
  http: ^0.13.0
  url_launcher: ^6.0.9
  firebase_messaging: ^10.0.4
  share: ^0.6.4+5
  flutter_map: ^0.13.1
  intl: ^0.17.0
  expandable: ^4.1.4
  email_validator: "^1.0.5"
  dio: ^4.0.0 #latest version
  image_gallery_saver: ^1.5.0
  permission_handler: ^8.1.4+1
  webview_flutter: ^2.0.10
  flutter_svg: ^0.22.0
  material_design_icons_flutter: ^4.0.5555
  flutter_html: ^2.1.0
  yaml: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_offline: ^0.3.0
  flutter_map_marker_cluster: ^0.4.0
  package_info: ">=0.4.0+16 <2.0.0"
  flip_card: ^0.4.4
  auto_size_text: ^2.1.0
  firebase_dynamic_links: ^2.0.7
  video_player: ^2.1.12
  carousel_slider: ^2.2.1
  cached_network_image: ^2.3.2+1
  drop_cap_text: ^1.0.7
  cupertino_icons: ^1.0.3
  quiver: ^3.0.0

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^4.1.4

  flutter_launcher_icons: "^0.9.0"
  hive_generator: ^1.1.0
  google_fonts: ^2.1.0

dependency_overrides:
  meta: 1.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"

google_fonts:
  fonts:
    - Jost
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config.yaml
    - assets/images/
    - assets/infoicons/

  fonts:
    - family: "Jost"
      fonts:
        - asset: "assets/fonts/googleFonts/Jost/Jost-100i.ttf"
          style: "italic"
          weight: 100
        - asset: "assets/fonts/googleFonts/Jost/Jost-200i.ttf"
          style: "italic"
          weight: 200
        - asset: "assets/fonts/googleFonts/Jost/Jost-300i.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/googleFonts/Jost/Jost-400i.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/googleFonts/Jost/Jost-500i.ttf"
          style: "italic"
          weight: 500
        - asset: "assets/fonts/googleFonts/Jost/Jost-600i.ttf"
          style: "italic"
          weight: 600
        - asset: "assets/fonts/googleFonts/Jost/Jost-700i.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/googleFonts/Jost/Jost-800i.ttf"
          style: "italic"
          weight: 800
        - asset: "assets/fonts/googleFonts/Jost/Jost-900i.ttf"
          style: "italic"
          weight: 900
        - asset: "assets/fonts/googleFonts/Jost/Jost-100.ttf"
          weight: 100
        - asset: "assets/fonts/googleFonts/Jost/Jost-200.ttf"
          weight: 200
        - asset: "assets/fonts/googleFonts/Jost/Jost-300.ttf"
          weight: 300
        - asset: "assets/fonts/googleFonts/Jost/Jost-400.ttf"
          weight: 400
        - asset: "assets/fonts/googleFonts/Jost/Jost-500.ttf"
          weight: 500
        - asset: "assets/fonts/googleFonts/Jost/Jost-600.ttf"
          weight: 600
        - asset: "assets/fonts/googleFonts/Jost/Jost-700.ttf"
          weight: 700
        - asset: "assets/fonts/googleFonts/Jost/Jost-800.ttf"
          weight: 800
        - asset: "assets/fonts/googleFonts/Jost/Jost-900.ttf"
          weight: 900
